name: Build and Deploy Angular to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./ClientApp
        run: npm ci

      - name: Build Angular app
        working-directory: ./ClientApp
        run: npm run build -- --configuration production --base-href=/

      - name: Copy 404.html for SPA fallback
        run: |
          cp ClientApp/dist/index.html ClientApp/dist/404.html || echo "no index.html at root"

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./ClientApp/dist
          force_orphan: true
